<a href="https://colab.research.google.com/github/Deepsphere-AI/BCA/blob/main/SEM-2/Data%20Science/Programs/Program_06_Numerical_Array_Processing_using_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 6: Install and perform a Numerical Array Processing using NumPy

In [ ]:
#Importing warnings to ignore them
import warnings
warnings.filterwarnings("ignore")

In [ ]:
#Installing numpy
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## Import libary

In [ ]:
#Importing numpy
import numpy as np

In [ ]:
print("\n***************** OutPut **********************\n")
# Create a 1D array
vAR_a = np.array([1, 2, 3, 4, 5])
print(vAR_a)

# Create a 2D array
vAR_b = np.array([[1, 2, 3], [4, 5, 6]])
print(vAR_b)


***************** OutPut **********************

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [ ]:
print("\n***************** OutPut **********************\n")
# Array shape
print(vAR_a.shape)
print(vAR_b.shape)

# Array data type
print(vAR_a.dtype)


***************** OutPut **********************

(5,)
(2, 3)
int64


In [ ]:
print("\n***************** OutPut **********************\n")
# Array arithmetic operations
vAR_c = vAR_a + 2
print(vAR_c)

vAR_d = vAR_a * 2
print(vAR_d)


***************** OutPut **********************

[3 4 5 6 7]
[ 2  4  6  8 10]


In [ ]:
print("\n***************** OutPut **********************\n")
# Array aggregations
print(vAR_a.sum())
print(vAR_a.mean())
print(vAR_a.max())
print(vAR_a.min())


***************** OutPut **********************

15
3.0
5
1
