<a href="https://colab.research.google.com/github/Deepsphere-AI/BCA/blob/main/SEM-2/Data%20Science/Programs/Program_06_Numerical_Array_Processing_using_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import numpy as np
print("\n***************** OutPut **********************\n")
# Create a 1D array
a = np.array([1, 2, 3, 4, 5])
print(a)

# Create a 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print("\n***************** OutPut **********************\n")


***************** OutPut **********************

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]

***************** OutPut **********************



In [4]:
print("\n***************** OutPut **********************\n")
# Array shape
print(a.shape)
print(b.shape)

# Array data type
print(a.dtype)
print("\n***************** OutPut **********************\n")


***************** OutPut **********************

(5,)
(2, 3)
int64

***************** OutPut **********************



In [5]:
print("\n***************** OutPut **********************\n")
# Array arithmetic operations
c = a + 2
print(c)

d = a * 2
print(d)
print("\n***************** OutPut **********************\n")


***************** OutPut **********************

[3 4 5 6 7]
[ 2  4  6  8 10]

***************** OutPut **********************



In [6]:
print("\n***************** OutPut **********************\n")
# Array aggregations
print(a.sum())
print(a.mean())
print(a.max())
print(a.min())
print("\n***************** OutPut **********************\n")


***************** OutPut **********************

15
3.0
5
1

***************** OutPut **********************

